CREATE TABLE IF NOT EXISTS resume (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  file_size BIGINT NOT NULL,
  file_type VARCHAR(20) NOT NULL,
  version_name VARCHAR(100) NOT NULL,
  resume_category VARCHAR(255),
  remark VARCHAR(500),
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_resume_version ON resume (version_name);
CREATE INDEX IF NOT EXISTS idx_resume_deleted ON resume (deleted);

CREATE TABLE IF NOT EXISTS job_application (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name VARCHAR(100) NOT NULL,
  position_name VARCHAR(120) NOT NULL,
  position_type VARCHAR(255),
  recruitment_type VARCHAR(80),
  resume_category VARCHAR(255),
  work_location VARCHAR(100),
  salary VARCHAR(80),
  source VARCHAR(80),
  job_link VARCHAR(500),
  job_description CLOB,
  progress_flow CLOB,
  current_status VARCHAR(80) NOT NULL DEFAULT '待投递',
  progress_result VARCHAR(40),
  progress_operated_time TIMESTAMP,
  applied_time TIMESTAMP,
  resume_id BIGINT,
  remark VARCHAR(1000),
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_application_company ON job_application (company_name);
CREATE INDEX IF NOT EXISTS idx_application_status ON job_application (current_status);
CREATE INDEX IF NOT EXISTS idx_application_type ON job_application (position_type);
CREATE INDEX IF NOT EXISTS idx_application_recruitment_type ON job_application (recruitment_type);
CREATE INDEX IF NOT EXISTS idx_application_resume ON job_application (resume_id);
CREATE INDEX IF NOT EXISTS idx_application_applied_time ON job_application (applied_time);
CREATE INDEX IF NOT EXISTS idx_application_deleted ON job_application (deleted);

CREATE TABLE IF NOT EXISTS interview_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT NOT NULL,
  round VARCHAR(60) NOT NULL,
  interview_time TIMESTAMP,
  interviewer VARCHAR(100),
  questions CLOB,
  result VARCHAR(100),
  difficulty INT,
  summary CLOB,
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_interview_job ON interview_record (job_id);
CREATE INDEX IF NOT EXISTS idx_interview_time ON interview_record (interview_time);
CREATE INDEX IF NOT EXISTS idx_interview_deleted ON interview_record (deleted);

CREATE TABLE IF NOT EXISTS interview_note (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  content CLOB,
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_note_job ON interview_note (job_id);
CREATE INDEX IF NOT EXISTS idx_note_updated ON interview_note (updated_time);
CREATE INDEX IF NOT EXISTS idx_note_deleted ON interview_note (deleted);

CREATE TABLE IF NOT EXISTS note_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT,
  type VARCHAR(20) NOT NULL,
  title VARCHAR(160) NOT NULL,
  file_name VARCHAR(255),
  file_path VARCHAR(500),
  content CLOB,
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_note_item_parent ON note_item (parent_id);
CREATE INDEX IF NOT EXISTS idx_note_item_type ON note_item (type);
CREATE INDEX IF NOT EXISTS idx_note_item_updated ON note_item (updated_time);
CREATE INDEX IF NOT EXISTS idx_note_item_deleted ON note_item (deleted);

CREATE TABLE IF NOT EXISTS reminder (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(160) NOT NULL,
  content VARCHAR(1000),
  remind_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP,
  schedule_type VARCHAR(40) DEFAULT '自定义',
  priority VARCHAR(20) DEFAULT '中',
  importance VARCHAR(20) DEFAULT '普通',
  related_application_id BIGINT,
  status VARCHAR(40) NOT NULL DEFAULT '未完成',
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_reminder_time ON reminder (remind_time);
CREATE INDEX IF NOT EXISTS idx_reminder_status ON reminder (status);
CREATE INDEX IF NOT EXISTS idx_reminder_deleted ON reminder (deleted);
